完善文档和功能
openGemini/openGemini-CM pull request #17
Opened 2023-09-30 03:45 UTC by 25hours886

完善项目文档，并调试项目功能，解决存在的bug。

2023-10-11 08:53 UTC, shilinlee requested changes

2023-10-11 08:53 UTC, shilinlee commented on README.md
> +
这个连起来，看着有点怪。环境准备可以提前单独提，ready完了，再介绍CM相关。

2023-10-11 08:53 UTC, shilinlee commented on README.md
> +- **User management**: log in, log out of the demo
```suggestion
- **User management**: login, logout of the demo
```

2023-10-28 13:45 UTC, xiangyu5632 commented on README.md
> +```bash
1. 开发环境和运行环境不要混淆，分开写具体的依赖软件和步骤，用户按照这个步骤来就一目了然
3. 服务启动说明一下如下是以什么进行举例。
4. 判断8086端口是否同意链接，建议改为用ts-cli客户端验证集群是否正常

2023-10-30 13:37 UTC, xiangyu5632 approved these changes

2023-10-30 13:39 UTC, merged